version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: monthly
        day: sunday
      open-pull-requests-limit: 3
      rebase-strategy: disabled
    - package-ecosystem: docker
      directory: /
      schedule:
        interval: monthly
